#PARAMETROS DE MENUS
ORO_INICIAL = 200
PRECIO_MAG = 40
PRECIO_GUE = 30
PRECIO_CAB = 30
PRECIO_ARMADURA = 10
PRECIO_PERGAMINO = 15
PRECIO_LANZA = 15
PRECIO_CURA = 200
CURAR_VIDA = 10
#variable constante
CANSANCIO = 10
#PARAMETROS DE CABALLERO
PROB_CABALLERO = 30 #sorprender al rival
RED_CAB = 14
ATQ_CAB = 12
#PARAMETROS MAGO 
PROB_MAG = 60
RED_MAG = 10
ATQ_MAG = 13
#PARAMETROS PALADIN 
PROB_PAL = 80
AUM_PAL = 30
#PARAMETROS MAGO DE BATALLA 
PROB_MDB = 10
DEF_MDB = 10

#PARAMETROS CABALLERO ARCANO 
PROB_CAR = 12
PROB_ATK_MAG = 100 - PROB_CAR
AUM_CAR = 10
####GANANDO ORITO 
ORO_GANADO = 15